permalink: :year-:month-:day-:title 

highlighter: pygments
markdown: kramdown

title : Orbitist
tagline: Science News in the Great Lakes
author : 
  name : Orbitist Support
  email : support@orbitist.com
  github : Orbitist
  twitter : TheOrbitist
  web : http://www.orbitist.com

production_url : orbitist.com/pieces

baseurl : http://orbitist.com/pieces
  
timezone : America/New_York
